---
- name: Install dependencies
  ansible.builtin.package:
    name:
      - nodejs
      - npm
      - git
      - ca-certificates
    state: present
  become: true

- name: Git Clone Juice Shop
  ansible.builtin.git:
    repo: https://github.com/juice-shop/juice-shop
    dest: /opt/juice-shop
    depth: 1
    version: master
  become: true
  register: clone_status
  
- name: Install Juice Shop
  community.general.npm:
    path: /opt/juice-shop
  become: true
  when: clone_status is changed

- name: Create Service File
  ansible.builtin.template:
    src: juiceshop.service.j2
    dest: /etc/systemd/system/juiceshop.service
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Launch Juice Shop
  ansible.builtin.systemd_service:
    name: juiceshop.service
    state: restarted
    enabled: true
    daemon_reload: true
  become: true